### ISSUE TITLE
Parity/compatibility: material-ui react components?

### ISSUE THREAD

**Issue by jpaas** [material-native/material-native#36]
Have you considered parity or at least interface compatibility with [material-ui for React](https://github.com/callemall/material-ui)?

This library has been around a while and is very well established.

Also for anyone who is trying to build a react-native app for ios/android and the web using something like [react-native-web](https://github.com/necolas/react-native-web), it would be soooo nice to be able to drop in components with compatible interfaces.

On our current project, we have created wrapper components that use the React components on the web, and use `react-native-material-kit` components for mobile. We mostly try to uphold the React component interfaces, and our wrapper components adapt the react-native-material-kit components to that interface.

The dream would be to not have to create these wrapper components at all, but to simply alias `material-native` for `material-ui` in a native build, or vice versa for a web build.

**Comment by jpaas** [comment]
And by the way, thank-you so much for taking on this project. It is sorely needed by the RN community.

**Comment by dantman** [comment]
I am at least using material-ui as one of the sources of ideas for the API (I look at react-native-material-kit, react-native-material-design, react-native, material-ui) and then do what I think looks like the best way to do it for react-native.

I'm not sure if a material-ui based API worthwhile to do for react-native-web. IIRC react-native-web translates react-native's View, Text, etc... components to web components. So theoretically material-native components might just be usable on the web (might need some compatibility fixes), instead of having to bother switching to material-ui.

But I did contemplate about matching the material-ui API, however I decided not to because of a few IMHO poor picks for the API and numerous ways that react-native's API is different than the API on the web 

* A huge portion of the material-ui API are css based props (`classes`, `*ClassName`, `fullWidth`) which are completely different to the way react-native does it.
* `<input>` and react-native's `<TextInput>` are almost nothing alike, so it doesn't make sense to try and use material-ui's API for this.
* Components like Drawers, AppBars, and BottomNavigation aren't really relevant since in the react-native context these are primarily the job of navigation libraries. material-native's role in these would be different, extending some of them to provide slightly more material versions and providing some interior components for things like navigation drawer items and headers.
* `<Image source>` works differently than `<img src srcSet>` so that part of `<Avatar>` doesn't translate.
* material-ui's `<Avatar>` doesn't bother handling icon or initial/text avatars directly, they use css and `children` for that. Which is more verbose and doesn't really work under react-native.
* material-ui's `<Avatar>` also doesn't have a `size` property, presumably they expect you to change the size with css, but that doesn't work in react-native because `borderRadius` doesn't have percentages in react-native so the component has to be responsible for setting the `width`, `height`, and `borderRadius` styles.
* IMHO Button and FAB should not be the same component like they are in material-ui, they are fairly different components.
* I don't like the use of `<FormControl>`, `<InputLabel>`, and `<Input>` instead of just a singular `<TextField>`, nor do I like the boolean `error` prop. It makes that code more verbose than it needs to be. I think material-ui does it because it's a holdover of the web where there are separate `<label>` and `<input>` elements underneath, which is irrelevant to react-native where we have to build 80% of this ourselves.
* react-native doesn't have underlying html components like tables for the numerous Grid/Table components in material-ui.
* The material-ui `<Typography>` component doesn't make any sense in react-native as opposed to the `typo` module and `<MaterialText>`.
* material-ui doesn't seem to bother implementing some of the Material Design spec, like handling for tall/dense typography for certain locales.
* `<Subheader/>` also appears to be missing.
* I wanted to make my components smarter than the components in all the other libraries, in particular you may notice that instead of expecting you to define a light or dark text color my components use the wcag's rules about contrast (which Material Design references) to automatically decide the text color based on the background.
* MuiTheme works differently than MaterialTheme, in ways that I don't believe are helpful for handling themes in react-native.

**Comment by jpaas** [comment]
Glad to hear you've looked at it in such depth. Much of this is true as we've had to find ways of adapting those components using our wrappers.

Perhaps you're right, the better goal might be `react-native-web` compatibility. If we could keep that on the goals/roadmap it would be much appreciated.

**Comment by dantman** [comment]
Ok, #37.
