### ISSUE TITLE
<Button> style override not working

### ISSUE THREAD

**Issue by kristfal** [material-native/material-native#40]
Any style applied to <Button> by the user is overridden by the root style of the component due to the current style order. This prevents us from setting the height and border radius of the button.

I'd guess something like this would provide most flexibility in `button.js`:

```jsx
style={[
	styles.root,
	raised ? styles.raised : styles.flat,
	raised && !disabled && elevation(2),
	{
		backgroundColor,
	},
        style,
]}
```

**Comment by dantman** [comment]
That is intentional. The Button component is a Material Design button and is not intended to support anything that doesn't follow the MD specs. The height and radius of a MD button are specified by the guides.

If you want a button that isn't part of material design you can just build your own button component out of low-level material components.

Here's an example of how I did exactly that for a large custom login button:
https://gist.github.com/dantman/f7dfd6c5db251ac68d8ab84a3cd75fe7
